services:
  postgres:
    image: postgres:latest
    container_name: node-express-blog
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: blog_db
    ports:
      - 5432:5432
